name: CI Pipeline
run-name: CI Pipeline
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      appType:
        required: true
        type: string
jobs:
  code-checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: azawsdevops/roboshop-${{ inputs.component }}
  
  app-dependencies:
    runs-on: self-hosted
    needs: code-checkout
    steps:
    - name: Downloading app dependencies
      run: |
        if [ ${{ inputs.appType }} == maven ]; then
          mvn clean package
        elif [ ${{ inputs.appType }} == nodejs ]; then
          npm install
        elif [ ${{ inputs.appType }} == python ]; then
          pip3 install -r requirement.txt
        fi
  
  code-quality:
    runs-on: self-hosted
    needs: app-dependencies
    steps:
    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v2
      with:
        url: http://vault-internal.cloudaws.shop:8200
        token: ${{ secrets.VAULT_TOKEN }}
        caCertificate: ${{ secrets.VAULT_TOKEN }}
#        secrets: |
#          github-action/data/azure_sp *;
        secrets: |
          github-action/data/azure_sp sonar_token | SONAR_TOKEN ;
    - name: Running Code quality checks
      run: |
        /opt/sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner -Dsonar.host.url=http://sonarqube-internal.cloudaws.shop:9000 -Dsonar.token=sqa_c54b102fbda5fc35c07ce398b131c43aed0 -Dsonar.projectKey=${{inputs.component}} -Dsonar.sources=. -Dsonar.language=${{ inputs.component }} -Dsonar.qualitygate.wait=true -Dsonar.java.binaries=./target
         
  unit tests:
    runs-on: self-hosted
    needs: app-dependencies
    steps:
    - name: testing unit test cases
      run: |
        echo "Running unit tests"
    
        
