name: deploy
run-name: Deployment
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repos
      uses: actions/checkout@v4
      with:
        repository: azawsdevops/roboshop-${{ inputs.component }}
