name: deploy
run-name: Deployment
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  dev:
    runs-on: self-hosted
    steps:
      uses: actions/checkout@v4
      with:
        component: cart
