name: deploy
run-name: Deployment
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  DEV:
    runs-on: self-hosted
    environment: DEV
    steps:
    - name: Checkout  repos
      uses: actions/checkout@v4
      with:
        repository: azawsdevops/aks-roboshop-helm
    - name: deployment
      run: |
        bash argocd.sh ${{ inputs.component }} dev cloudaws.azurecr.io/roboshop-${{ inputs.component }}:${GITHUB_SHA}
      
  
  QA:
    runs-on: self-hosted
    environment: QA
    needs: DEV
    steps:
    - run: echo QA
  
  UAT:
    runs-on: self-hosted
    environment: UAT
    needs: QA
    steps:
    - run: echo UAT
  
  
  PROD:
    runs-on: self-hosted
    environment: PROD
    needs: UAT
    steps:
    - run: echo PROD
