name: deploy
run-name: Deployment
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      name: checkout code
      run: ls -l
      with:
        component: cart
