name: Terraform
on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string
    secrets:
      VAULT_TOKEN: 
        required: true
  
jobs:
  action:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v2
      with:
        url: http://vault-internal.cloudaws.shop:8200
        token: ${{ secrets.VAULT_TOKEN }}
        caCertificate: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          github-action/data/azure_sp *;

    - run: make dev-${{ inputs.action }} vault_token=${{ secrets.VAULT_TOKEN }}
